apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/pnetwork/pnbase//monitor/?ref=master
#    - ../../../pnbase/monitor
#    - https://github.com/pnetwork/pnbase//fluentd/?ref=master
#    - https://github.com/pnetwork/pnbase//kafka/?ref=master
#    - https://github.com/pnetwork/pnbase//zookeeper/?ref=master

resources:
- namespace.yaml
- clusterRoleBinding.yaml

namespace: __NS_DEFAULT__

images:
- name: __IMAGE/pentium-fluentd
  newName: dockerhub.pentium.network/gde/pentium-fluentd
  newTag: 1.1.3-gde.10

# to be replaced
#configMapGenerator:
#- name: host-info
#  literals:
#  - data01=192.168.89.95

patchesJson6902:
- path: patch_env.yaml
  target:
    group: extensions
    kind: DaemonSet
    name: fluentd
    version: v1beta1
- path: patch_certs.yaml
  target:
    kind: Secret
    name: fluentd-certs
    version: v1
