apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-preview-elasticsearch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: gde/kustomize/workflow-preview/elasticsearch/
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: workflow-preview
