apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/pnetwork/pnbase//monitor/?ref=master

resources:
- namespace.yaml
- clusterRoleBinding.yaml

namespace: workflow-preview

images:
- name: __IMAGE/pentium-fluentd
  newName: dockerhub.pentium.network/gde/pentium-fluentd
  newTag: 1.1.15-p1202-5

# to be replaced
#configMapGenerator:
#- name: host-info
#  literals:
#  - data01=192.168.89.95

patchesJson6902:
- path: patch_env.yaml
  target:
    group: extensions
    kind: DaemonSet
    name: fluentd
    version: v1beta1
- path: patch_certs.yaml
  target:
    kind: Secret
    name: fluentd-certs
    version: v1
- path: patch_account.yaml
  target:
    kind: ServiceAccount
    name: fluentd-__NS_DEFAULT__
    version: v1
