kind: Kustomization

namespace: workflow-preview-openfaas-fn

bases:
  - https://github.com/pnetwork/pnbase//openfaas/?ref=master

secretGenerator:
- name: pn-faas-secret
  behavior: replace
  files:
  - config.json
  type: Opaque

# openfaas
images:
- name: __IMAGE/mobileadapter
  newName: dockerhub.pentium.network/blcks/mobileadapter
  newTag: 0.0.1
- name: __IMAGE/commandevents
  newName: dockerhub.pentium.network/gde/commandevents
  newTag: 0.1.1561731909612
- name: __IMAGE/commandworkflowcontroller
  newName: dockerhub.pentium.network/gde/commandworkflowcontroller
  newTag: 0.1.1562224018531
- name: __IMAGE/commandworkflows
  newName: dockerhub.pentium.network/gde/commandworkflows
  newTag: 0.1.1562223686124
- name: __IMAGE/queryworkflows
  newName: dockerhub.pentium.network/gde/queryworkflows
  newTag: 0.1.1562223686124
- name: __IMAGE/balances
  newName: dockerhub.pentium.network/master/balances
  newTag: 0.103.20190620182637
- name: __IMAGE/bindresolverkey
  newName: dockerhub.pentium.network/master/bindresolverkey
  newTag: 0.98.20190529001322
- name: __IMAGE/buildresolverrelation
  newName: dockerhub.pentium.network/master/buildresolverrelation
  newTag: 0.98.20190529001322
- name: __IMAGE/buildsubdomainsmapping
  newName: dockerhub.pentium.network/master/buildsubdomainsmapping
  newTag: 0.95.10.20190523004610
- name: __IMAGE/bulkgetsubdomains
  newName: dockerhub.pentium.network/master/bulkgetsubdomains
  newTag: 0.95.10.20190523004610
- name: __IMAGE/bulkmigration
  newName: dockerhub.pentium.network/master/bulkmigration
  newTag: 0.98.20190529001322
- name: __IMAGE/bulkorigins
  newName: dockerhub.pentium.network/master/bulkorigins
  newTag: 0.98.1.20190530094415
- name: __IMAGE/bulkpurge
  newName: dockerhub.pentium.network/master/bulkpurge
  newTag: 0.105.20190627190106
- name: __IMAGE/bulkreqheaders
  newName: dockerhub.pentium.network/master/bulkreqheaders
  newTag: 0.98.1.20190530094415
- name: __IMAGE/bulkresolver
  newName: dockerhub.pentium.network/master/bulkresolver
  newTag: 0.98.20190529001322
- name: __IMAGE/bulksyncdomain
  newName: dockerhub.pentium.network/master/bulksyncdomain
  newTag: 0.98.20190529001322
- name: __IMAGE/bulksyncfqdn
  newName: dockerhub.pentium.network/master/bulksyncfqdn
  newTag: 0.98.1.20190530094415
- name: __IMAGE/chatbotkit
  newName: dockerhub.pentium.network/master/chatbotkit
  newTag: 0.102.20190619094905
- name: __IMAGE/checkexpiredhosts
  newName: dockerhub.pentium.network/master/checkexpiredhosts
  newTag: 0.101.20190613200203
- name: __IMAGE/checkexpiredhostsadapter
  newName: dockerhub.pentium.network/master/checkexpiredhostsadapter
  newTag: 0.101.20190613200203
- name: __IMAGE/checkexpiredtime
  newName: dockerhub.pentium.network/master/checkexpiredtime
  newTag: 0.101.20190613200203
- name: __IMAGE/checkexpiredtimeadapter
  newName: dockerhub.pentium.network/master/checkexpiredtimeadapter
  newTag: 0.101.20190613200203
- name: __IMAGE/cloud
  newName: dockerhub.pentium.network/master/cloud
  newTag: 5ad5d5e
- name: __IMAGE/cloudcallback
  newName: dockerhub.pentium.network/master/cloudcallback
  newTag: 5ad5d5e
- name: __IMAGE/cloudevents
  newName: dockerhub.pentium.network/master/cloudevents
  newTag: 0.105.20190627184418
- name: __IMAGE/commandaccounts
  newName: dockerhub.pentium.network/master/commandaccounts
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandattachments
  newName: dockerhub.pentium.network/master/commandattachments
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandattachmentshosts
  newName: dockerhub.pentium.network/master/commandattachmentshosts
  newTag: 74.5.20190315211504
- name: __IMAGE/commandauths
  newName: dockerhub.pentium.network/master/commandauths
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandautocompletes
  newName: dockerhub.pentium.network/master/commandautocompletes
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandbotchannels
  newName: dockerhub.pentium.network/master/commandbotchannels
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandcallbackfailure
  newName: dockerhub.pentium.network/master/commandcallbackfailure
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandcdncontents
  newName: dockerhub.pentium.network/master/commandcdncontents
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandcdns
  newName: dockerhub.pentium.network/master/commandcdns
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandchannels
  newName: dockerhub.pentium.network/master/commandchannels
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandchatbots
  newName: dockerhub.pentium.network/master/commandchatbots
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandcloudaccount
  newName: dockerhub.pentium.network/master/commandcloudaccount
  newTag: 0.106.3.20190702170152
- name: __IMAGE/commandcloudproviders
  newName: dockerhub.pentium.network/master/commandcloudproviders
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandcloudtools
  newName: dockerhub.pentium.network/master/commandcloudtools
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandcredentials
  newName: dockerhub.pentium.network/master/commandcredentials
  newTag: 74.5.20190315211504
- name: __IMAGE/commanddatabases
  newName: dockerhub.pentium.network/master/commanddatabases
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commanddomainresolvers
  newName: dockerhub.pentium.network/master/commanddomainresolvers
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commanddomains
  newName: dockerhub.pentium.network/master/commanddomains
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandfqdns
  newName: dockerhub.pentium.network/master/commandfqdns
  newTag: 5ad5d5e
- name: __IMAGE/commandhosts
  newName: dockerhub.pentium.network/master/commandhosts
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandimproviders
  newName: dockerhub.pentium.network/master/commandimproviders
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandkeypairs
  newName: dockerhub.pentium.network/master/commandkeypairs
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandkms
  newName: dockerhub.pentium.network/master/commandkms
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandplaybooklogs
  newName: dockerhub.pentium.network/master/commandplaybooklogs
  newTag: e3ab8bd
- name: __IMAGE/commandplaybooks
  newName: dockerhub.pentium.network/master/commandplaybooks
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandpolicies
  newName: dockerhub.pentium.network/master/commandpolicies
  newTag: 0.106.3.20190702170152
- name: __IMAGE/commandprojects
  newName: dockerhub.pentium.network/master/commandprojects
  newTag: 0.106.2.20190702135454
- name: __IMAGE/commandprotect
  newName: dockerhub.pentium.network/master/commandprotect
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandrbacconditions
  newName: dockerhub.pentium.network/master/commandrbacconditions
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandrbacroles
  newName: dockerhub.pentium.network/master/commandrbacroles
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandregions
  newName: dockerhub.pentium.network/master/commandregions
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandrelationmap
  newName: dockerhub.pentium.network/master/commandrelationmap
  newTag: 5ad5d5e
- name: __IMAGE/commandsubdomains
  newName: dockerhub.pentium.network/master/commandsubdomains
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandtunnels
  newName: dockerhub.pentium.network/master/commandtunnels
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandusers
  newName: dockerhub.pentium.network/master/commandusers
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandworkflowgc
  newName: dockerhub.pentium.network/master/commandworkflowgc
  newTag: 0.106.0.20190701205640
- name: __IMAGE/commandworkflowtemplates
  newName: dockerhub.pentium.network/master/commandworkflowtemplates
  newTag: 0.106.0.20190701205640
- name: __IMAGE/credentials
  newName: dockerhub.pentium.network/master/credentials
  newTag: 5ad5d5e
- name: __IMAGE/deleteaccounts
  newName: dockerhub.pentium.network/master/deleteaccounts
  newTag: 5ad5d5e
- name: __IMAGE/deletedomains
  newName: dockerhub.pentium.network/master/deletedomains
  newTag: 5ad5d5e
- name: __IMAGE/deletehosts
  newName: dockerhub.pentium.network/master/deletehosts
  newTag: 5ad5d5e
- name: __IMAGE/deleteprovider
  newName: dockerhub.pentium.network/master/deleteprovider
  newTag: 5ad5d5e
- name: __IMAGE/domaincsv
  newName: dockerhub.pentium.network/master/domaincsv
  newTag: 5ad5d5e
- name: __IMAGE/domainmanagement
  newName: dockerhub.pentium.network/master/domainmanagement
  newTag: 0.103.20190620182637
- name: __IMAGE/domainsapi
  newName: dockerhub.pentium.network/master/domainsapi
  newTag: 5ad5d5e
- name: __IMAGE/domainservices
  newName: dockerhub.pentium.network/master/domainservices
  newTag: 5ad5d5e
- name: __IMAGE/domainsverification
  newName: dockerhub.pentium.network/master/domainsverification
  newTag: 5ad5d5e
- name: __IMAGE/domainsync
  newName: dockerhub.pentium.network/master/domainsync
  newTag: 5ad5d5e
- name: __IMAGE/domainwebhook
  newName: dockerhub.pentium.network/master/domainwebhook
  newTag: 5ad5d5e
- name: __IMAGE/fileupload
  newName: dockerhub.pentium.network/master/fileupload
  newTag: 0.98.20190529001322
- name: __IMAGE/fqdnsclone
  newName: dockerhub.pentium.network/master/fqdnsclone
  newTag: 5ad5d5e
- name: __IMAGE/getaccounts
  newName: dockerhub.pentium.network/master/getaccounts
  newTag: 5ad5d5e
- name: __IMAGE/getcdns
  newName: dockerhub.pentium.network/master/getcdns
  newTag: 0.101.20190613200203
- name: __IMAGE/getcloudaccounts
  newName: dockerhub.pentium.network/master/getcloudaccounts
  newTag: v0.101.1.20190613191348
- name: __IMAGE/getdomains
  newName: dockerhub.pentium.network/master/getdomains
  newTag: 0.98.20190529001322
- name: __IMAGE/getproviders
  newName: dockerhub.pentium.network/master/getproviders
  newTag: 5ad5d5e
- name: __IMAGE/gfwcheck
  newName: dockerhub.pentium.network/master/gfwcheck
  newTag: v0.99.8.20190610110113
- name: __IMAGE/icpcheck
  newName: dockerhub.pentium.network/master/icpcheck
  newTag: v0.99.8.20190610110113
- name: __IMAGE/invocations
  newName: dockerhub.pentium.network/master/invocations
  newTag: 0.98.20190529001322
- name: __IMAGE/kms
  newName: dockerhub.pentium.network/master/kms
  newTag: 5ad5d5e
- name: __IMAGE/logsapi
  newName: dockerhub.pentium.network/master/logsapi
  newTag: 5ad5d5e
- name: __IMAGE/notification
  newName: dockerhub.pentium.network/master/notification
  newTag: 0.101.20190613200203
- name: __IMAGE/patchaccount
  newName: dockerhub.pentium.network/master/patchaccount
  newTag: 5ad5d5e
- name: __IMAGE/patchdomainsbyid
  newName: dockerhub.pentium.network/master/patchdomainsbyid
  newTag: 5ad5d5e
- name: __IMAGE/patchhostwebhook
  newName: dockerhub.pentium.network/master/patchhostwebhook
  newTag: 5ad5d5e
- name: __IMAGE/patchprovider
  newName: dockerhub.pentium.network/master/patchprovider
  newTag: 5ad5d5e
- name: __IMAGE/patchserversbyid
  newName: dockerhub.pentium.network/master/patchserversbyid
  newTag: 5ad5d5e
- name: __IMAGE/playbooklogsapi
  newName: dockerhub.pentium.network/master/playbooklogsapi
  newTag: 5ad5d5e
- name: __IMAGE/playbookzip
  newName: dockerhub.pentium.network/master/playbookzip
  newTag: 5ad5d5e
- name: __IMAGE/postaccounts
  newName: dockerhub.pentium.network/master/postaccounts
  newTag: 5ad5d5e
- name: __IMAGE/postdomains
  newName: dockerhub.pentium.network/master/postdomains
  newTag: 5ad5d5e
- name: __IMAGE/postlogs
  newName: dockerhub.pentium.network/master/postlogs
  newTag: 5ad5d5e
- name: __IMAGE/postprovider
  newName: dockerhub.pentium.network/master/postprovider
  newTag: 5ad5d5e
- name: __IMAGE/postservers
  newName: dockerhub.pentium.network/master/postservers
  newTag: 5ad5d5e
- name: __IMAGE/putlogsbyid
  newName: dockerhub.pentium.network/master/putlogsbyid
  newTag: 5ad5d5e
- name: __IMAGE/queryaccounts
  newName: dockerhub.pentium.network/master/queryaccounts
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryautocompletes
  newName: dockerhub.pentium.network/master/queryautocompletes
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querybotchannels
  newName: dockerhub.pentium.network/master/querybotchannels
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querycdncontents
  newName: dockerhub.pentium.network/master/querycdncontents
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querycdns
  newName: dockerhub.pentium.network/master/querycdns
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querychannels
  newName: dockerhub.pentium.network/master/querychannels
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querychatbots
  newName: dockerhub.pentium.network/master/querychatbots
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querycloudaccount
  newName: dockerhub.pentium.network/master/querycloudaccount
  newTag: 0.106.3.20190702170152
- name: __IMAGE/querycloudproviders
  newName: dockerhub.pentium.network/master/querycloudproviders
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querydatabases
  newName: dockerhub.pentium.network/master/querydatabases
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querydatabaseversions
  newName: dockerhub.pentium.network/master/querydatabaseversions
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querydomainresolvers
  newName: dockerhub.pentium.network/master/querydomainresolvers
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querydomains
  newName: dockerhub.pentium.network/master/querydomains
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryevents
  newName: dockerhub.pentium.network/master/queryevents
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryfqdns
  newName: dockerhub.pentium.network/master/queryfqdns
  newTag: 5ad5d5e
- name: __IMAGE/queryhosts
  newName: dockerhub.pentium.network/master/queryhosts
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryimproviders
  newName: dockerhub.pentium.network/master/queryimproviders
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querykeypairs
  newName: dockerhub.pentium.network/master/querykeypairs
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querykms
  newName: dockerhub.pentium.network/master/querykms
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querymaps
  newName: dockerhub.pentium.network/master/querymaps
  newTag: 5ad5d5e
- name: __IMAGE/queryplaybookgrouplogs
  newName: dockerhub.pentium.network/master/queryplaybookgrouplogs
  newTag: e3ab8bd
- name: __IMAGE/queryplaybooklogs
  newName: dockerhub.pentium.network/master/queryplaybooklogs
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryplaybooks
  newName: dockerhub.pentium.network/master/queryplaybooks
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querypolicies
  newName: dockerhub.pentium.network/master/querypolicies
  newTag: 0.106.3.20190702170152
- name: __IMAGE/queryprojects
  newName: dockerhub.pentium.network/master/queryprojects
  newTag: 0.106.2.20190702135454
- name: __IMAGE/queryrbacroles
  newName: dockerhub.pentium.network/master/queryrbacroles
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryregions
  newName: dockerhub.pentium.network/master/queryregions
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryservices
  newName: dockerhub.pentium.network/master/queryservices
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querysubdomains
  newName: dockerhub.pentium.network/master/querysubdomains
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querysyslogs
  newName: dockerhub.pentium.network/master/querysyslogs
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querytags
  newName: dockerhub.pentium.network/master/querytags
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querytools
  newName: dockerhub.pentium.network/master/querytools
  newTag: 0.94.20190516181959
- name: __IMAGE/querytunnels
  newName: dockerhub.pentium.network/master/querytunnels
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryusers
  newName: dockerhub.pentium.network/master/queryusers
  newTag: 0.106.0.20190701205640
- name: __IMAGE/querywebsshlogs
  newName: dockerhub.pentium.network/master/querywebsshlogs
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryworkflowlogs
  newName: dockerhub.pentium.network/master/queryworkflowlogs
  newTag: 0.106.0.20190701205640
- name: __IMAGE/queryworkflowtemplates
  newName: dockerhub.pentium.network/master/queryworkflowtemplates
  newTag: 0.106.0.20190701205640
- name: __IMAGE/resolverwebhook
  newName: dockerhub.pentium.network/master/resolverwebhook
  newTag: 5ad5d5e
- name: __IMAGE/sendmessage
  newName: dockerhub.pentium.network/master/sendmessage
  newTag: 0.101.20190613200203
- name: __IMAGE/serverapi
  newName: dockerhub.pentium.network/master/serverapi
  newTag: 5ad5d5e
- name: __IMAGE/servercsv
  newName: dockerhub.pentium.network/master/servercsv
  newTag: 5ad5d5e
- name: __IMAGE/servicecdns
  newName: dockerhub.pentium.network/master/servicecdns
  newTag: 73bf4a0
- name: __IMAGE/syncallcdns
  newName: dockerhub.pentium.network/master/syncallcdns
  newTag: 0.98.20190529001322
- name: __IMAGE/syncallfqdns
  newName: dockerhub.pentium.network/master/syncallfqdns
  newTag: 0.98.1.20190530094415
- name: __IMAGE/syncassets
  newName: dockerhub.pentium.network/master/syncassets
  newTag: v0.101.1.20190613191348
- name: __IMAGE/synccdns
  newName: dockerhub.pentium.network/master/synccdns
  newTag: 73bf4a0
- name: __IMAGE/syncfqdns
  newName: dockerhub.pentium.network/master/syncfqdns
  newTag: 5ad5d5e
- name: __IMAGE/syncinstances
  newName: dockerhub.pentium.network/master/syncinstances
  newTag: 0.98.20190529001322
- name: __IMAGE/syslogsapi
  newName: dockerhub.pentium.network/master/syslogsapi
  newTag: 5ad5d5e
- name: __IMAGE/tunneleventhandler
  newName: dockerhub.pentium.network/master/tunneleventhandler
  newTag: v.0.104.20190625170832
- name: __IMAGE/tunnelscommand
  newName: dockerhub.pentium.network/master/tunnelscommand
  newTag: 5ad5d5e
- name: __IMAGE/tunnelsquery
  newName: dockerhub.pentium.network/master/tunnelsquery
  newTag: 5ad5d5e
- name: __IMAGE/updateyearning
  newName: dockerhub.pentium.network/master/updateyearning
  newTag: 0.99.20190603163731
- name: __IMAGE/usergraphapi
  newName: dockerhub.pentium.network/master/usergraphapi
  newTag: 5ad5d5e
- name: __IMAGE/weixincheck
  newName: dockerhub.pentium.network/master/weixincheck
  newTag: 0.104.20190625171431
- name: __IMAGE/wfexception
  newName: dockerhub.pentium.network/master/wfexception
  newTag: 0.98.1.20190530094415
- name: __IMAGE/trigger
  newName: dockerhub.pentium.network/pentium/trigger
  newTag: 0.96.20
